name: Basic CI

on:
  push:
    branches: [ main, develop, funcshape ]
  pull_request:
    branches: [ main, develop ]

jobs:
  basic-test:
    name: Basic Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install -e . --no-deps

    - name: Run basic functionality test
      run: |
        cd testing
        python test_basic_functionality.py



    - name: Run fast tests
      run: |
        cd testing
        python run_tests.py --fast
      continue-on-error: true
