name: Continuous Integration

on:
  push:
    branches: [ main, develop, funcshape ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10']
        # Temporarily exclude Windows due to Unicode issues
        # Will re-enable after fixing encoding problems

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('testing/requirements-test.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Install package
      run: |
        pip install -e .

    - name: Run basic functionality test
      run: |
        cd testing
        python test_basic_functionality.py

    - name: Run full test suite with coverage
      run: |
        cd testing
        python -m pytest tests/ -v --tb=short --cov=apdist --cov-report=xml --cov-report=term-missing
      continue-on-error: true

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      uses: codecov/codecov-action@v4
      with:
        file: ./testing/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
