name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        pip install -e .
        pip install -r testing/requirements-test.txt

    - name: Create docs directory structure
      run: |
        mkdir -p docs/source
        mkdir -p docs/build

    - name: Generate API documentation
      run: |
        sphinx-apidoc -o docs/source apdist/
        
    - name: Create Sphinx configuration
      run: |
        cat > docs/source/conf.py << 'EOF'
        import os
        import sys
        sys.path.insert(0, os.path.abspath('../../'))

        project = 'apdist'
        copyright = '2024, Kiran Vaddi'
        author = 'Kiran Vaddi'
        release = '1.0'

        extensions = [
            'sphinx.ext.autodoc',
            'sphinx.ext.viewcode',
            'sphinx.ext.napoleon',
            'sphinx_autodoc_typehints',
        ]

        templates_path = ['_templates']
        exclude_patterns = []

        html_theme = 'sphinx_rtd_theme'
        html_static_path = ['_static']

        autodoc_default_options = {
            'members': True,
            'undoc-members': True,
            'show-inheritance': True,
        }
        EOF

    - name: Create main documentation file
      run: |
        cat > docs/source/index.rst << 'EOF'
        apdist Documentation
        ===================

        A light-weight repository to compute Amplitude Phase distance between two functions.

        .. toctree::
           :maxdepth: 2
           :caption: Contents:

           modules

        Installation
        ------------

        .. code-block:: bash

           pip install git+https://github.com/kiranvad/Amplitude-Phase-Distance.git

        Quick Start
        -----------

        .. code-block:: python

           import numpy as np
           from apdist import AmplitudePhaseDistance

           # Create test functions
           t = np.linspace(0, 1, 101)
           f1 = np.sin(2 * np.pi * t)
           f2 = np.sin(2 * np.pi * t + np.pi/4)

           # Compute distances
           amplitude_dist, phase_dist = AmplitudePhaseDistance(t, f1, f2)

        API Reference
        =============

        .. automodule:: apdist
           :members:

        Indices and tables
        ==================

        * :ref:`genindex`
        * :ref:`modindex`
        * :ref:`search`
        EOF

    - name: Build documentation
      run: |
        cd docs
        sphinx-build -b html source build/html

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/build/html/

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html/
