name: Installation Check

on: [push, pull_request, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -m pip install --upgrade pip setuptools wheel build

      - run: pip install .

      - run: python -c "import from apdist.distances import AmplitudePhaseDistance"
      
      - run: python -m build

      - run: pip install dist/*.whl

      - run: python -c "import from apdist.distances import AmplitudePhaseDistance"
"