name: Simple Test

on:
  push:
    branches: [ main, develop, funcshape ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib

    - name: Test imports
      run: |
        python -c "import numpy; print('numpy OK')"
        python -c "import scipy; print('scipy OK')"
        python -c "import matplotlib; print('matplotlib OK')"
        python -c "import sys; sys.path.insert(0, '.'); import apdist; print('[SUCCESS] Package imports successfully')"
        python -c "import sys; sys.path.insert(0, '.'); from apdist import AmplitudePhaseDistance; print('[SUCCESS] Main function imports successfully')"

    - name: Test basic functionality
      run: |
        python -c "
        import sys; sys.path.insert(0, '.')
        import numpy as np
        import warnings
        from apdist import AmplitudePhaseDistance
        t = np.linspace(0, 1, 51)
        f1 = np.sin(2 * np.pi * t)
        f2 = np.sin(2 * np.pi * t + np.pi/4)
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            da, dp = AmplitudePhaseDistance(t, f1, f2)
        print(f'[SUCCESS] Distance computation works: da={da:.4f}, dp={dp:.4f}')
        assert da >= 0 and dp >= 0
        print('[SUCCESS] All assertions passed')
        "
